stages:
  get_bdb_2024_data:
    cmd: kaggle competitions download -c nfl-big-data-bowl-2024 -p data/
    outs:
    - data/nfl-big-data-bowl-2024.zip

  unzip_bdb_2024_data:
    cmd: unzip data/nfl-big-data-bowl-2024.zip -d data/bdb_2024/
    deps:
    - data/nfl-big-data-bowl-2024.zip
    outs:
    - data/bdb_2024

  prep_data:
    cmd: rye run python src/prep_data.py
    deps:
    - src/prep_data.py
    - data/bdb_2024/
    outs:
    - data/split_prepped_data/

  precompute_datasets: # this might take an hour
    cmd: rye run python src/datasets.py
    deps:
    - src/datasets.py
    - data/split_prepped_data/
    outs:
    - data/datasets/transformer/
    - data/datasets/zoo/

  train_zoo_models:
    cmd: rye run python src/train.py --model_type zoo

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/zoo/
    outs:
    - data/models/zoo/

  train_transformer_models:
    cmd: rye run python src/train.py --model_type transformer

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/transformer
    outs:
    - data/models/transformer/


  precompute_datasets_advanced: # this might take an hour
    cmd: rye run python src/datasets.py --advanced
    deps:
    - src/datasets.py
    - data/split_prepped_data/
    outs:
    - data/datasets/transformer_advanced/
    # - data/datasets/zoo_advanced/

  # train_zoo_model_with_advanced:
  #   cmd: rye run python src/train.py --model_type zoo --advanced

  #   deps:
  #   - src/train.py
  #   - src/datasets.py
  #   - src/models.py
  #   - data/datasets/zoo_advanced/
  #   outs:
  #   - data/models/zoo_advanced

  train_transformer_models_advanced:
    cmd: rye run python src/train.py --model_type transformer --advanced

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/transformer_advanced/
    outs:
    - data/models/transformer_advanced

  pick_best_models:
    cmd: rye run python src/pick_best_models.py

    deps:
    - src/pick_best_models.py
    - src/datasets.py
    - src/models.py

    - data/models/
    outs:
    - data/best_models/