stages:
  get_bdb_2024_data:
    cmd: kaggle competitions download -c nfl-big-data-bowl-2024 -p data/
    outs:
    - data/nfl-big-data-bowl-2024.zip

  unzip_bdb_2024_data:
    cmd: unzip data/nfl-big-data-bowl-2024.zip -d data/bdb_2024/
    deps:
    - data/nfl-big-data-bowl-2024.zip
    outs:
    - data/bdb_2024

  prep_data:
    cmd: rye run python src/prep_data.py
    deps:
    - src/prep_data.py
    - data/bdb_2024/
    outs:
    - data/split_prepped_data/

  precompute_datasets: # this might take an hour
    cmd: rye run python src/datasets.py
    deps:
    - src/datasets.py
    - data/split_prepped_data/
    outs:
    - data/datasets/transformer/
    - data/datasets/zoo/

  train_zoo_models:
    cmd: rye run python src/train.py --model_type zoo

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/zoo/
    outs:
    - data/models/zoo/:
        persist: true

  train_transformer_models:
    cmd: rye run python src/train.py --model_type transformer

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/transformer
    outs:
    - data/models/transformer/:
        persist: true


  precompute_datasets_with_play: # this might take an hour
    cmd: rye run python src/datasets.py --play_features
    deps:
    - src/datasets.py
    - data/split_prepped_data/
    outs:
    - data/datasets/transformer_play/
    - data/datasets/zoo_play/

  # train_zoo_model_with_play:
  #   cmd: rye run python src/train.py --model_type zoo --play_features

  #   deps:
  #   - src/train.py
  #   - src/datasets.py
  #   - src/models.py
  #   - data/datasets/zoo_play/
  #   outs:
  #   - data/models/zoo_play/:
  #       persist: true

  train_transformer_model_with_play:
    cmd: rye run python src/train.py --model_type transformer --play_features

    deps:
    - src/train.py
    - src/datasets.py
    - src/models.py
    - data/datasets/transformer_play/
    outs:
    - data/models/transformer_play/:
        persist: true

  pick_best_models:
    cmd: rye run python src/pick_best_models.py

    deps:
    - src/pick_best_models.py
    - src/datasets.py
    - src/models.py

    - data/models/
    outs:
    - data/best_models/